---
title: "Wrangling data on charter fisheries"
author: "Ben Cresswell"
format: html
editor: visual
---



# Packages
```{r}
library(tidyverse)
library(janitor)
```


# To download data go to:
https://qfish.fisheries.qld.gov.au/query/charter-catch-and-effort/table

# Load data

```{r}
charter <- 
  read_csv("../data/export.csv") |>
  row_to_names(row_number = 1) |> # Variable names are meaningless, so remove
  clean_names() # But we want 
head(charter)
```

```{r}
combination <- charter |>
  select(na | contains("Combination")) |>
  row_to_names(row_number = 1) |>
  mutate(across(is.character, as.numeric)) |>
  filter(!is.na(CalendarYear))

diving <- charter |>
  select(na | contains("diving")) |>
  row_to_names(row_number = 1) |>
  mutate(across(is.character, as.numeric)) |>
  filter(!is.na(CalendarYear))
```




```{r}
shark_program <- 
  read_csv("../data/shark.csv") |>
  row_to_names(row_number = 2, remove_rows_above = FALSE) |> # Variable names are meaningless, so remove
  clean_names() # But we want 
head(shark_program)
```
```{r}
shark_catch <- 
  shark_program |>
  select(area | contains("shark")) |>
  row_to_names(row_number = 1) |>
  rename(Area = 1) |>
  mutate(across(-c(Area), as.numeric)) 
  
turtle_catch <- 
  shark_program |>
  select(area | contains("turtle")) |>
  row_to_names(row_number = 1) |>
  rename(Area = 1) |>
  mutate(across(-c(Area), as.numeric)) 

mammal_catch <- 
  shark_program |>
  select(area | contains("mammal")) |>
  row_to_names(row_number = 1) |>
  rename(Area = 1) |>
  mutate(across(-c(Area), as.numeric)) 

other_catch <- 
  shark_program |>
  select(area | contains("other")) |>
  row_to_names(row_number = 1) |>
  rename(Area = 1) |>
  mutate(across(-c(Area), as.numeric)) 

head(shark_catch, n = 2)
```

# Pivot wide tibbles longer
```{r}
shark_catch_long <- 
shark_catch |>
  pivot_longer(!Area, names_to = "Year", values_to = "Nos")

turtle_catch_long <- 
  turtle_catch |>
  pivot_longer(!Area, names_to = "Year", values_to = "Nos")

```

# Make stats tibbles
```{r}
shark_stats <- 
shark_catch_long |>
  filter(Area != "Grand Total") |>
  group_by(Year) |>
  summarise(Mean = mean(Nos, na.rm = TRUE),
            SD = sd(Nos, na.rm = TRUE)) |>
  mutate(Year = as.numeric(Year)) |>
  mutate(Taxa = "Sharks")

turtle_stats <- 
turtle_catch_long |>
  filter(Area != "Grand Total") |>
  group_by(Year) |>
  summarise(Mean = mean(Nos, na.rm = TRUE),
            SD = sd(Nos, na.rm = TRUE)) |>
  mutate(Year = as.numeric(Year)) |>
  mutate(Taxa = "Turtles")

combine_stats <- 
  bind_rows(shark_stats, turtle_stats)
  
```


```{r}
ggplot(data = combine_stats, aes(x =Year, y = Mean, fill = Taxa, shape = Taxa), colour = "black") +
  geom_line() +
  geom_pointrange(aes(ymin = Mean - SD, ymax = Mean + SD)) +
    scale_shape_manual(values = c(23, 24))

```


